language: node_js
matrix:
  include:
    - node_js: "node"
sudo: required
dist: trusty
before_script:
  - mkdir -p vendors
  - npm install -g web-components-tester bower
  - export DISPLAY=:99.0
  - wget 'https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots' -O chrome.zip && unzip chrome.zip
  - export PATH="$PATH:$(pwd)/chrome-linux"
  - sh -e /etc/init.d/xvfb start
  - bower i
script:
  - wct -l chrome